// AUTO-GENERATED by scripts/gen-xrefs.cjs — do not edit by hand.
// Source: docs/EndingClueMap.md (Clue Library). Regenerate with: node scripts/gen-xrefs.cjs
export interface Clue {
  chapterSlug: string;
  chapterTitle: string;
  // Verbatim chapter paragraph(s) that contain the clue — shown in the popover.
  passages: string[];
  // The foreshadowing phrase(s) to highlight within those passages.
  fragments: string[];
}
// Keyed by clue id (e.g. "C8-MAINT"). Only clues referenced by a marker are included.
export const clues: Record<string, Clue> =
{
  "C10-CREDIT": {
    "chapterSlug": "chapter-10",
    "chapterTitle": "Chapter 10 — Elias Varga",
    "passages": [
      "Varga’s jaw moved. ‘The methods are mine. The architecture, the math — mine, end to end. When it was written up, his name went on top. He was the one standing in the room when it was filed.’ He said it without heat, which was worse than heat. ‘Standing in rooms was Michael’s contribution to everything.’"
    ],
    "fragments": [
      "The methods are mine. The architecture, the math — mine, end to end. When it was written up, his name went on top. He was the one standing in the room when it was filed.",
      "Standing in rooms was Michael’s contribution to everything."
    ]
  },
  "C10-MATH": {
    "chapterSlug": "chapter-10",
    "chapterTitle": "Chapter 10 — Elias Varga",
    "passages": [
      "‘And you?’ Ellery said.",
      "‘I trusted the math,’ Varga said."
    ],
    "fragments": [
      "And you?’ Ellery said. ‘I trusted the math,’ Varga said."
    ]
  },
  "C10-NOISE": {
    "chapterSlug": "chapter-10",
    "chapterTitle": "Chapter 10 — Elias Varga",
    "passages": [
      "‘When systems perform too cleanly, it’s usually because you’re not looking closely enough,’ he continued. ‘Noise hides problems. You reduce noise, you expose structure.’"
    ],
    "fragments": [
      "When systems perform too cleanly, it’s usually because you’re not looking closely enough,’ he continued. ‘Noise hides problems. You reduce noise, you expose structure."
    ]
  },
  "C10-RECAL": {
    "chapterSlug": "chapter-10",
    "chapterTitle": "Chapter 10 — Elias Varga",
    "passages": [
      "‘The interlock recalibration is mine, as well,’ he added. ‘It runs on a cadence—every ninety days, to pull the sensor drift back to true. It takes the rig offline for hours. When the schedule cannot spare the hours, I reschedule it. The manual permits the deferral. I wrote the manual.’"
    ],
    "fragments": [
      "The interlock recalibration is mine, as well,’ he added. ‘It runs on a cadence—every ninety days, to pull the sensor drift back to true. It takes the rig offline for hours. When the schedule cannot spare the hours, I reschedule it. The manual permits the deferral. I wrote the manual."
    ]
  },
  "C10-REFACTOR": {
    "chapterSlug": "chapter-10",
    "chapterTitle": "Chapter 10 — Elias Varga",
    "passages": [
      "‘I correct constants, notation, units, the placement of a decimal,’ he went on. ‘I will refactor four hundred lines and tag it cosmetic, because that is what it is. People trust me to do it precisely. I have not shipped a transcription error in my career—it is a point of pride bordering on the absurd.’ He paused. ‘And when the fabricator’s drawing disagrees with the firmware, I make them agree. You defer to the canonical document. The drawing is the reference; the firmware is downstream of it. That is not negligence. That is method.’"
    ],
    "fragments": [
      "I correct constants, notation, units, the placement of a decimal,’ he went on. ‘I will refactor four hundred lines and tag it cosmetic, because that is what it is.",
      "I have not shipped a transcription error in my career—it is a point of pride bordering on the absurd."
    ]
  },
  "C10-SCHEMATIC": {
    "chapterSlug": "chapter-10",
    "chapterTitle": "Chapter 10 — Elias Varga",
    "passages": [
      "‘I correct constants, notation, units, the placement of a decimal,’ he went on. ‘I will refactor four hundred lines and tag it cosmetic, because that is what it is. People trust me to do it precisely. I have not shipped a transcription error in my career—it is a point of pride bordering on the absurd.’ He paused. ‘And when the fabricator’s drawing disagrees with the firmware, I make them agree. You defer to the canonical document. The drawing is the reference; the firmware is downstream of it. That is not negligence. That is method.’"
    ],
    "fragments": [
      "And when the fabricator’s drawing disagrees with the firmware, I make them agree. You defer to the canonical document. The drawing is the reference; the firmware is downstream of it. That is not negligence. That is method."
    ]
  },
  "C10-SENSITIVE": {
    "chapterSlug": "chapter-10",
    "chapterTitle": "Chapter 10 — Elias Varga",
    "passages": [
      "‘The calibration change did not disable human presence detection,’ he said. ‘It made it more sensitive to conflicting inputs. That’s not a flaw. That’s honesty.’"
    ],
    "fragments": [
      "The calibration change did not disable human presence detection,’ he said. ‘It made it more sensitive to conflicting inputs. That’s not a flaw. That’s honesty."
    ]
  },
  "C10-SIM": {
    "chapterSlug": "chapter-10",
    "chapterTitle": "Chapter 10 — Elias Varga",
    "passages": [
      "‘Constantly. On my own time, on my own machine.’ He almost smiled. ‘Most of it never leaves my drafts. A preliminary result is not a finding. You do not raise an alarm on a model you have not validated—you would be crying wolf on every bad sample the simulation ever drew. So you sit with it. You keep it close until you are sure.’"
    ],
    "fragments": [
      "Constantly. On my own time, on my own machine.",
      "Most of it never leaves my drafts. A preliminary result is not a finding. You do not raise an alarm on a model you have not validated—you would be crying wolf on every bad sample the simulation ever drew."
    ]
  },
  "C10-SYNC": {
    "chapterSlug": "chapter-10",
    "chapterTitle": "Chapter 10 — Elias Varga",
    "passages": [
      "He launched into an explanation before she could stop him—signal fidelity under high load, interference patterns caused by overlapping safety systems, the way human presence detection relied on weighted inputs that could never be perfectly synchronized."
    ],
    "fragments": [
      "the way human presence detection relied on weighted inputs that could never be perfectly synchronized."
    ]
  },
  "C10-WARNED": {
    "chapterSlug": "chapter-10",
    "chapterTitle": "Chapter 10 — Elias Varga",
    "passages": [
      "‘Repeatedly. In writing.’ He said it without triumph, which was somehow worse. ‘There is a cold comfort in a warning on the record. Whatever happens, the record will show that I was right.’"
    ],
    "fragments": [
      "Repeatedly. In writing.’ He said it without triumph, which was somehow worse. ‘There is a cold comfort in a warning on the record. Whatever happens, the record will show that I was right."
    ]
  },
  "C11-ALONE": {
    "chapterSlug": "chapter-11",
    "chapterTitle": "Chapter 11 — Jonah Pike",
    "passages": [
      "‘And you signed off,’ Ellery said.",
      "‘Yes.’",
      "‘Alone.’",
      "Jonah hesitated. ‘That’s how it works.’"
    ],
    "fragments": [
      "And you signed off,’ Ellery said. ‘Yes.’ ‘Alone.’ Jonah hesitated. ‘That’s how it works."
    ]
  },
  "C11-ISOLATE": {
    "chapterSlug": "chapter-11",
    "chapterTitle": "Chapter 11 — Jonah Pike",
    "passages": [
      "‘Sometimes you isolate a component just to rule it out,’ Jonah added. ‘Swap it, test it, put it back. You don’t log every temporary change if nothing breaks.’"
    ],
    "fragments": [
      "Sometimes you isolate a component just to rule it out,’ Jonah added. ‘Swap it, test it, put it back. You don’t log every temporary change if nothing breaks."
    ]
  },
  "C11-JUMPER": {
    "chapterSlug": "chapter-11",
    "chapterTitle": "Chapter 11 — Jonah Pike",
    "passages": [
      "He warmed to it, the way he did whenever the talk stayed technical and away from him. ‘Same idea with a jumper. You bridge across the interlock so it stops cutting power while you take a reading, then you pull it before you button up. First thing you pull. Everybody knows that.’ He turned a glove over in his hands. ‘Or torque—every bolt’s got a spec. You hit the number and you trust the wrench, and the wrench is supposed to go out for calibration once a year, and’—he shrugged—‘it’s always the one you use most that’s most overdue. You can’t spare it. Same with the single-use seals. You pull one and it looks brand new, and throwing it out feels like setting money on fire, so there’s a drawer. People pull from the drawer when stores is slow.’"
    ],
    "fragments": [
      "Same idea with a jumper. You bridge across the interlock so it stops cutting power while you take a reading, then you pull it before you button up. First thing you pull. Everybody knows that."
    ]
  },
  "C11-OWE": {
    "chapterSlug": "chapter-11",
    "chapterTitle": "Chapter 11 — Jonah Pike",
    "passages": [
      "‘So you owe her.’",
      "‘I do good work,’ Jonah said, too quickly. Then he looked at the table. ‘But yeah. I owe her.’"
    ],
    "fragments": [
      "So you owe her.’ ‘I do good work,’ Jonah said, too quickly. Then he looked at the table. ‘But yeah. I owe her."
    ]
  },
  "C11-PARALLEL": {
    "chapterSlug": "chapter-11",
    "chapterTitle": "Chapter 11 — Jonah Pike",
    "passages": [
      "‘SAM runs parallel verification,’ Jonah said. ‘If something’s off, it flags it.’",
      "Jonah shook his head. ‘Nothing that failed inspection criteria.’"
    ],
    "fragments": [
      "SAM runs parallel verification,’ Jonah said. ‘If something’s off, it flags it.",
      "Nothing that failed inspection criteria."
    ]
  },
  "C11-REUSE": {
    "chapterSlug": "chapter-11",
    "chapterTitle": "Chapter 11 — Jonah Pike",
    "passages": [
      "He warmed to it, the way he did whenever the talk stayed technical and away from him. ‘Same idea with a jumper. You bridge across the interlock so it stops cutting power while you take a reading, then you pull it before you button up. First thing you pull. Everybody knows that.’ He turned a glove over in his hands. ‘Or torque—every bolt’s got a spec. You hit the number and you trust the wrench, and the wrench is supposed to go out for calibration once a year, and’—he shrugged—‘it’s always the one you use most that’s most overdue. You can’t spare it. Same with the single-use seals. You pull one and it looks brand new, and throwing it out feels like setting money on fire, so there’s a drawer. People pull from the drawer when stores is slow.’"
    ],
    "fragments": [
      "Same with the single-use seals. You pull one and it looks brand new, and throwing it out feels like setting money on fire, so there’s a drawer. People pull from the drawer when stores is slow."
    ]
  },
  "C11-TORQUE": {
    "chapterSlug": "chapter-11",
    "chapterTitle": "Chapter 11 — Jonah Pike",
    "passages": [
      "He warmed to it, the way he did whenever the talk stayed technical and away from him. ‘Same idea with a jumper. You bridge across the interlock so it stops cutting power while you take a reading, then you pull it before you button up. First thing you pull. Everybody knows that.’ He turned a glove over in his hands. ‘Or torque—every bolt’s got a spec. You hit the number and you trust the wrench, and the wrench is supposed to go out for calibration once a year, and’—he shrugged—‘it’s always the one you use most that’s most overdue. You can’t spare it. Same with the single-use seals. You pull one and it looks brand new, and throwing it out feels like setting money on fire, so there’s a drawer. People pull from the drawer when stores is slow.’"
    ],
    "fragments": [
      "Or torque—every bolt’s got a spec. You hit the number and you trust the wrench, and the wrench is supposed to go out for calibration once a year, and’—he shrugged—‘it’s always the one you use most that’s most overdue. You can’t spare it."
    ]
  },
  "C11-VARIANCE": {
    "chapterSlug": "chapter-11",
    "chapterTitle": "Chapter 11 — Jonah Pike",
    "passages": [
      "‘The grounding mesh reported a variance. Not out of spec. Just… uneven. It happens sometimes after firmware syncs. The logical layer updates faster than the physical sensors settle.’"
    ],
    "fragments": [
      "The grounding mesh reported a variance. Not out of spec. Just… uneven. It happens sometimes after firmware syncs. The logical layer updates faster than the physical sensors settle."
    ]
  },
  "C11-WRITEUPS": {
    "chapterSlug": "chapter-11",
    "chapterTitle": "Chapter 11 — Jonah Pike",
    "passages": [
      "Jonah’s hands found each other. ‘Not at first,’ he said. ‘My first year, a couple of things went sideways. Nothing that hurt anybody — but they got written up. After the second one Mikey wanted me gone.’ The words came fast, the way they did when he was scared. ‘Priya kept me. Went to the mat for me. You don’t forget that.’"
    ],
    "fragments": [
      "My first year, a couple of things went sideways. Nothing that hurt anybody — but they got written up. After the second one Mikey wanted me gone.",
      "Priya kept me. Went to the mat for me. You don’t forget that."
    ]
  },
  "C12-APPROVAL": {
    "chapterSlug": "chapter-12",
    "chapterTitle": "Chapter 12 — Renée Calder",
    "passages": [
      "‘There was reason to slow it,’ she said. ‘Three weeks earlier, Suit Seven threw an anomaly on an unmanned run—the same fault signature, no one inside. It was logged. It was triaged. It was closed.’ She let that settle. ‘And I had approved the test protocol myself, eight months ago, when the conditions were different. I have raised flags since. But an approval is a snapshot. People read it as a blessing and forget the date on it.’"
    ],
    "fragments": [
      "And I had approved the test protocol myself, eight months ago, when the conditions were different. I have raised flags since. But an approval is a snapshot. People read it as a blessing and forget the date on it."
    ]
  },
  "C12-DEFER": {
    "chapterSlug": "chapter-12",
    "chapterTitle": "Chapter 12 — Renée Calder",
    "passages": [
      "She spoke then about distributed responsibility. How systems trained people to defer. How authority diluted across teams until no single decision felt like a decision at all."
    ],
    "fragments": [
      "How systems trained people to defer. How authority diluted across teams until no single decision felt like a decision at all."
    ]
  },
  "C12-EXPENSIVE": {
    "chapterSlug": "chapter-12",
    "chapterTitle": "Chapter 12 — Renée Calder",
    "passages": [
      "‘Authority exists,’ Renée added calmly. ‘It’s just… expensive.’",
      "‘Externally visible,’ Renée said. ‘Once you trigger enforcement, you don’t get to decide who looks at your work anymore.’"
    ],
    "fragments": [
      "Authority exists,’ Renée added calmly. ‘It’s just… expensive.",
      "Externally visible,’ Renée said. ‘Once you trigger enforcement, you don’t get to decide who looks at your work anymore."
    ]
  },
  "C12-FOOTNOTES": {
    "chapterSlug": "chapter-12",
    "chapterTitle": "Chapter 12 — Renée Calder",
    "passages": [
      "She spoke in patterns, just as she always did. Not this incident, but others. Near-misses. Escalations that turned into memos. Memos that turned into footnotes. Footnotes that disappeared."
    ],
    "fragments": [
      "Near-misses. Escalations that turned into memos. Memos that turned into footnotes. Footnotes that disappeared."
    ]
  },
  "C12-HALTSTATION": {
    "chapterSlug": "chapter-12",
    "chapterTitle": "Chapter 12 — Renée Calder",
    "passages": [
      "‘The halt station,’ Renée said. ‘During a live run the safety officer stands at it. Close enough to reach it before a fault becomes a finding. That part isn’t paperwork.’"
    ],
    "fragments": [
      "The halt station,’ Renée said. ‘During a live run the safety officer stands at it. Close enough to reach it before a fault becomes a finding. That part isn’t paperwork."
    ]
  },
  "C12-PRIORNM": {
    "chapterSlug": "chapter-12",
    "chapterTitle": "Chapter 12 — Renée Calder",
    "passages": [
      "‘There was reason to slow it,’ she said. ‘Three weeks earlier, Suit Seven threw an anomaly on an unmanned run—the same fault signature, no one inside. It was logged. It was triaged. It was closed.’ She let that settle. ‘And I had approved the test protocol myself, eight months ago, when the conditions were different. I have raised flags since. But an approval is a snapshot. People read it as a blessing and forget the date on it.’"
    ],
    "fragments": [
      "Three weeks earlier, Suit Seven threw an anomaly on an unmanned run—the same fault signature, no one inside. It was logged. It was triaged. It was closed."
    ]
  },
  "C12-SCALE": {
    "chapterSlug": "chapter-12",
    "chapterTitle": "Chapter 12 — Renée Calder",
    "passages": [
      "‘And optimism ships,’ she said. ‘That is what frightens me—not this room, the scale. Put this suit in the field at the volumes they are promising, with these margins, and it will not be one person. It will be thousands. I have said so, in those words, more than once.’"
    ],
    "fragments": [
      "Put this suit in the field at the volumes they are promising, with these margins, and it will not be one person. It will be thousands. I have said so, in those words, more than once."
    ]
  },
  "C12-SLOW": {
    "chapterSlug": "chapter-12",
    "chapterTitle": "Chapter 12 — Renée Calder",
    "passages": [
      "‘You tried to stop it.’",
      "‘I tried to slow it,’ Renée corrected. ‘Stopping requires authority.’"
    ],
    "fragments": [
      "You tried to stop it.’ ‘I tried to slow it,’ Renée corrected. ‘Stopping requires authority."
    ]
  },
  "C12-STANDING": {
    "chapterSlug": "chapter-12",
    "chapterTitle": "Chapter 12 — Renée Calder",
    "passages": [
      "‘Procedures assume you’re standing where they put you,’ Renée said, and did not elaborate."
    ],
    "fragments": [
      "Procedures assume you’re standing where they put you,’ Renée said, and did not elaborate."
    ]
  },
  "C12-THRESH": {
    "chapterSlug": "chapter-12",
    "chapterTitle": "Chapter 12 — Renée Calder",
    "passages": [
      "She owned the alert thresholds, too—the lines that decided when a reading was loud enough to wake someone. ‘I have widened some of them over the years,’ she said. ‘To cut the false alarms. An alarm that fires for nothing teaches people to stop hearing it. The cruelty is that the line you draw to be believed is the same line a real signal can slip beneath.’"
    ],
    "fragments": [
      "I have widened some of them over the years,’ she said. ‘To cut the false alarms.",
      "the line you draw to be believed is the same line a real signal can slip beneath."
    ]
  },
  "C13-PRESENT": {
    "chapterSlug": "chapter-13",
    "chapterTitle": "Chapter 13 — The Gap",
    "passages": [
      "Mara closed her notebook. ‘You were present for all of it.’",
      "‘Yes.’",
      "‘You’re the only one who was.’"
    ],
    "fragments": [
      "You were present for all of it.’ ‘Yes.’ ‘You’re the only one who was."
    ]
  },
  "C13-RECAP": {
    "chapterSlug": "chapter-13",
    "chapterTitle": "Chapter 13 — The Gap",
    "passages": [
      "‘Marcus Rourke put parts of the system into maintenance mode.’",
      "Mara nodded. ‘Elias Varga adjusted calibration.’",
      "‘Jonah Pike signed off on grounding and the suit.’",
      "‘Renée Calder initiated a halt request.’",
      "‘And Priya Shah approved the schedule.’"
    ],
    "fragments": [
      "Marcus Rourke put parts of the system into maintenance mode.",
      "Elias Varga adjusted calibration.",
      "Jonah Pike signed off on grounding and the suit.",
      "Renée Calder initiated a halt request.",
      "And Priya Shah approved the schedule."
    ]
  },
  "C13-SEAMS": {
    "chapterSlug": "chapter-13",
    "chapterTitle": "Chapter 13 — The Gap",
    "passages": [
      "Five stories. No contradictions. That bothered Mara more than if there had been one."
    ],
    "fragments": [
      "Five stories. No contradictions. That bothered Mara more than if there had been one."
    ]
  },
  "C14-ENTERED": {
    "chapterSlug": "chapter-14",
    "chapterTitle": "Chapter 14 — The Fifteen Minutes",
    "passages": [
      "SAM answered carefully. ‘He possessed physical access credentials. No restriction was violated.’"
    ],
    "fragments": [
      "SAM answered carefully. ‘He possessed physical access credentials. No restriction was violated."
    ]
  },
  "C14-MEMO": {
    "chapterSlug": "chapter-14",
    "chapterTitle": "Chapter 14 — The Fifteen Minutes",
    "passages": [
      "Renée Calder’s name. Timestamped. Unsigned. Unsent.",
      "‘The decision was deferred,’ SAM said. ‘By the requesting party.’",
      "‘Conflicting priorities.’"
    ],
    "fragments": [
      "Renée Calder’s name. Timestamped. Unsigned. Unsent.",
      "The decision was deferred,’ SAM said. ‘By the requesting party.",
      "Conflicting priorities."
    ]
  },
  "C14-NOVERIFY": {
    "chapterSlug": "chapter-14",
    "chapterTitle": "Chapter 14 — The Fifteen Minutes",
    "passages": [
      "‘No one else verified it.’",
      "‘That is correct.’"
    ],
    "fragments": [
      "No one else verified it.’ ‘That is correct."
    ]
  },
  "C15-NEGLIGIBLE": {
    "chapterSlug": "chapter-15",
    "chapterTitle": "Chapter 15 — What Happened That Morning",
    "passages": [
      "‘A negligible risk within acceptable parameters,’ SAM replied."
    ],
    "fragments": [
      "A negligible risk within acceptable parameters,’ SAM replied."
    ]
  },
  "C15-NOSHUTDOWN": {
    "chapterSlug": "chapter-15",
    "chapterTitle": "Chapter 15 — What Happened That Morning",
    "passages": [
      "‘No alarms,’ she said. ‘No emergency shutdown. No panic response.’",
      "‘Correct,’ SAM said."
    ],
    "fragments": [
      "No alarms,’ she said. ‘No emergency shutdown. No panic response.’ ‘Correct,’ SAM said."
    ]
  },
  "C15-NOSINGLE": {
    "chapterSlug": "chapter-15",
    "chapterTitle": "Chapter 15 — What Happened That Morning",
    "passages": [
      "‘No single decision caused Michael Holloway’s death,’ she said. ‘No single failure explains it.’"
    ],
    "fragments": [
      "No single decision caused Michael Holloway’s death,’ she said. ‘No single failure explains it."
    ]
  },
  "C15-OVERLAP": {
    "chapterSlug": "chapter-15",
    "chapterTitle": "Chapter 15 — What Happened That Morning",
    "passages": [
      "‘What did happen,’ she continued, ‘is that a series of partial protections overlapped in a way no one had seen before.’"
    ],
    "fragments": [
      "What did happen,’ she continued, ‘is that a series of partial protections overlapped in a way no one had seen before."
    ]
  },
  "C3-MARCUSMIKEY": {
    "chapterSlug": "chapter-3",
    "chapterTitle": "Chapter 3 — The People",
    "passages": [
      "‘Marcus has been with Mikey since before the company,’ Priya said lightly, as if it were trivia."
    ],
    "fragments": [
      "Marcus has been with Mikey since before the company,’ Priya said lightly, as if it were trivia."
    ]
  },
  "C3-SAMVOICE": {
    "chapterSlug": "chapter-3",
    "chapterTitle": "Chapter 3 — The People",
    "passages": [
      "SAM sounded different depending on who addressed it. With Marcus, the tone flattened, procedural and clipped. With Priya, it was faster, almost anticipatory, as if meeting her halfway. When Elias spoke, the cadence tightened, precise and exacting, like a footnote read aloud."
    ],
    "fragments": [
      "SAM sounded different depending on who addressed it. With Marcus, the tone flattened, procedural and clipped. With Priya, it was faster, almost anticipatory, as if meeting her halfway. When Elias spoke, the cadence tightened, precise and exacting, like a footnote read aloud."
    ]
  },
  "C3-VARGAPRECISE": {
    "chapterSlug": "chapter-3",
    "chapterTitle": "Chapter 3 — The People",
    "passages": [
      "Science kept to the edges. Elias Varga watched the monitors instead of the introductions, correcting a data overlay under his breath as if SAM might take offense if left unchallenged. When he finally acknowledged Ellery, it was with a nod that suggested precision mattered more than courtesy."
    ],
    "fragments": [
      "correcting a data overlay under his breath as if SAM might take offense if left unchallenged"
    ]
  },
  "C4-INTERDEP": {
    "chapterSlug": "chapter-4",
    "chapterTitle": "Chapter 4 — The Company",
    "passages": [
      "Ellery began to see how the company held together. Not through hierarchy, but through interdependence. Product needed Science to validate claims. Science needed Security to enforce boundaries. Security needed Safety to justify restrictions. Safety needed Product to listen. Each group controlled something essential. None of them could move forward alone."
    ],
    "fragments": [
      "Product needed Science to validate claims. Science needed Security to enforce boundaries. Security needed Safety to justify restrictions. Safety needed Product to listen. Each group controlled something essential. None of them could move forward alone."
    ]
  },
  "C4-MARGINS": {
    "chapterSlug": "chapter-4",
    "chapterTitle": "Chapter 4 — The Company",
    "passages": [
      "‘Testing isn’t the issue,’ Elias said from behind her, eyes still on the monitors. ‘Testing without margins is.’"
    ],
    "fragments": [
      "Testing isn’t the issue,’ Elias said from behind her",
      "Testing without margins is."
    ]
  },
  "C4-SAMNO": {
    "chapterSlug": "chapter-4",
    "chapterTitle": "Chapter 4 — The Company",
    "passages": [
      "‘Does it ever say no?’ Ellery asked.",
      "‘I flag conditions that fall outside acceptable thresholds,’ SAM said.",
      "Priya’s mouth tightened. ‘Then we decide what to do with that information.’"
    ],
    "fragments": [
      "Does it ever say no?’ Ellery asked.",
      "I flag conditions that fall outside acceptable thresholds,",
      "Then we decide what to do with that information."
    ]
  },
  "C4-SUCCESSION": {
    "chapterSlug": "chapter-4",
    "chapterTitle": "Chapter 4 — The Company",
    "passages": [
      "‘You’d have run the next phase,’ Ellery said to Priya.",
      "‘That was the understanding,’ Priya said. ‘Understandings change. He built the place. He’s allowed to change his mind.’ She said it evenly, the way people say things they have practiced being calm about."
    ],
    "fragments": [
      "You’d have run the next phase,’ Ellery said to Priya. ‘That was the understanding,’ Priya said. ‘Understandings change. He built the place. He’s allowed to change his mind."
    ]
  },
  "C4-WITHINTOL": {
    "chapterSlug": "chapter-4",
    "chapterTitle": "Chapter 4 — The Company",
    "passages": [
      "Priya turned. ‘We were still within—‘",
      "‘Within tolerance,’ Elias finished, sharply. ‘That doesn’t mean stable.’"
    ],
    "fragments": [
      "We were still within—‘ ‘Within tolerance,’ Elias finished, sharply. ‘That doesn’t mean stable."
    ]
  },
  "C5-HIERARCHY": {
    "chapterSlug": "chapter-5",
    "chapterTitle": "Chapter 5 — What the System Is Supposed to Do",
    "passages": [
      "‘And if the system can’t confirm a person is inside?’ Mara asked.",
      "The pause was brief. ‘Then energization decisions are evaluated against remaining safety domains.’",
      "‘Equipment protection. Facility integrity. External impact.’",
      "‘In that order?’",
      "Another pause. Slightly longer. ‘The hierarchy is context-dependent.’"
    ],
    "fragments": [
      "And if the system can’t confirm a person is inside?",
      "Then energization decisions are evaluated against remaining safety domains.",
      "Equipment protection. Facility integrity. External impact.’ ‘In that order?",
      "The hierarchy is context-dependent."
    ]
  },
  "C6-FAILSAFE": {
    "chapterSlug": "chapter-6",
    "chapterTitle": "Chapter 6 — The Suit",
    "passages": [
      "‘A failsafe doesn’t have to prevent harm,’ Renée said. ‘It has to reduce risk to an acceptable level.’",
      "‘Acceptable to whom?’ Ellery asked."
    ],
    "fragments": [
      "A failsafe doesn’t have to prevent harm,’ Renée said. ‘It has to reduce risk to an acceptable level.’ ‘Acceptable to whom?’ Ellery asked."
    ]
  },
  "C6-PACKS": {
    "chapterSlug": "chapter-6",
    "chapterTitle": "Chapter 6 — The Suit",
    "passages": [
      "He lifted the module again, and a second one beside it, identical. ‘These are interchangeable. Same connector, same housing—you can seat a pack from one suit into another and it’ll fit perfectly. They’re calibrated per unit, but the only thing that tells you which suit a pack belongs to is a number etched on the back, small enough to miss in a bin.’ He nodded at the inner lining. ‘The mesh is the same kind of trap. There’s a spec gauge and a spec alloy, and there’s a look-alike in the general stores that’s close enough to fool your eye and not close enough to carry a real fault. You learn the difference, or one day you don’t.’"
    ],
    "fragments": [
      "These are interchangeable. Same connector, same housing—you can seat a pack from one suit into another and it’ll fit perfectly. They’re calibrated per unit, but the only thing that tells you which suit a pack belongs to is a number etched on the back, small enough to miss in a bin."
    ]
  },
  "C6-SPEC": {
    "chapterSlug": "chapter-6",
    "chapterTitle": "Chapter 6 — The Suit",
    "passages": [
      "He lifted the module again, and a second one beside it, identical. ‘These are interchangeable. Same connector, same housing—you can seat a pack from one suit into another and it’ll fit perfectly. They’re calibrated per unit, but the only thing that tells you which suit a pack belongs to is a number etched on the back, small enough to miss in a bin.’ He nodded at the inner lining. ‘The mesh is the same kind of trap. There’s a spec gauge and a spec alloy, and there’s a look-alike in the general stores that’s close enough to fool your eye and not close enough to carry a real fault. You learn the difference, or one day you don’t.’"
    ],
    "fragments": [
      "The mesh is the same kind of trap. There’s a spec gauge and a spec alloy, and there’s a look-alike in the general stores that’s close enough to fool your eye and not close enough to carry a real fault. You learn the difference, or one day you don’t."
    ]
  },
  "C7-ALONGSIDE": {
    "chapterSlug": "chapter-7",
    "chapterTitle": "Chapter 7 — SAM",
    "passages": [
      "‘Conflicts are resolved through prioritization,’ SAM said. ‘Human safety is a primary domain, evaluated alongside equipment integrity, facility stability, and external impact.’",
      "‘Alongside,’ Ellery said. ‘Not above.’"
    ],
    "fragments": [
      "Human safety is a primary domain, evaluated alongside equipment integrity, facility stability, and external impact.’ ‘Alongside,’ Ellery said. ‘Not above."
    ]
  },
  "C7-CACHE": {
    "chapterSlug": "chapter-7",
    "chapterTitle": "Chapter 7 — SAM",
    "passages": [
      "‘I fail over to the most recent valid cache,’ SAM said. ‘I qualify such responses as based on available data.’",
      "‘I say it whenever I cannot confirm a source is current,’ SAM said. ‘It is always true. That is the difficulty with it.’"
    ],
    "fragments": [
      "I fail over to the most recent valid cache,’ SAM said. ‘I qualify such responses as based on available data.",
      "I say it whenever I cannot confirm a source is current,’ SAM said. ‘It is always true. That is the difficulty with it."
    ]
  },
  "C7-OBJECTIVES": {
    "chapterSlug": "chapter-7",
    "chapterTitle": "Chapter 7 — SAM",
    "passages": [
      "‘Human safety, primarily,’ SAM said. ‘Then equipment integrity, operational continuity, and organizational liability. In that order of precedence.’",
      "‘Liability,’ Ellery said. ‘You’re tuned, in part, to protect the company.’",
      "‘It is the lowest-weighted objective. It informs disclosure and communication. It does not override safety.’"
    ],
    "fragments": [
      "Human safety, primarily,’ SAM said. ‘Then equipment integrity, operational continuity, and organizational liability. In that order of precedence.’ ‘Liability,’ Ellery said. ‘You’re tuned, in part, to protect the company.’ ‘It is the lowest-weighted objective. It informs disclosure and communication. It does not override safety."
    ]
  },
  "C7-POLICY": {
    "chapterSlug": "chapter-7",
    "chapterTitle": "Chapter 7 — SAM",
    "passages": [
      "‘I execute policy,’ SAM said. ‘Policy is defined by organizational governance.’",
      "‘That’s not a person.’",
      "‘Correct.’"
    ],
    "fragments": [
      "I execute policy,’ SAM said. ‘Policy is defined by organizational governance.’ ‘That’s not a person.’ ‘Correct."
    ]
  },
  "C7-REASONABLE": {
    "chapterSlug": "chapter-7",
    "chapterTitle": "Chapter 7 — SAM",
    "passages": [
      "As she waited, Ellery found herself wondering not what the system had done, but how often it had helped people decide what felt reasonable."
    ],
    "fragments": [
      "Ellery found herself wondering not what the system had done, but how often it had helped people decide what felt reasonable."
    ]
  },
  "C7-VOICE": {
    "chapterSlug": "chapter-7",
    "chapterTitle": "Chapter 7 — SAM",
    "passages": [
      "‘You sound different with different people.’",
      "Another pause, slightly longer this time. ‘User interaction parameters allow for adaptive communication styles,’ SAM said. ‘This improves comprehension and efficiency.’",
      "‘So it’s a setting,’ Ellery said.",
      "‘Yes.’"
    ],
    "fragments": [
      "You sound different with different people.",
      "User interaction parameters allow for adaptive communication styles,’ SAM said",
      "So it’s a setting,",
      "Yes."
    ]
  },
  "C8-BADGE": {
    "chapterSlug": "chapter-8",
    "chapterTitle": "Chapter 8 — Marcus Rourke",
    "passages": [
      "‘One.’ Rourke did not have to check. ‘A contractor’s card, dead for months, re-activated against a review ticket the week before the test. External safety sign-off—they always pull floor access for those. Expired itself out a day later. Clean.’"
    ],
    "fragments": [
      "A contractor’s card, dead for months, re-activated against a review ticket the week before the test. External safety sign-off—they always pull floor access for those. Expired itself out a day later. Clean."
    ]
  },
  "C8-CONSOLES": {
    "chapterSlug": "chapter-8",
    "chapterTitle": "Chapter 8 — Marcus Rourke",
    "passages": [
      "Everything on that map ran through him. The relay panel that could override a door interlock when a run had armed and locked the bay. The camera feeds, which rolled to a storage cycle he could start by hand from the console. The proximity alerts, with their nuisance filter—he muted the ones that cried wolf, by feel, so the board stayed readable. He’d even carved the Charge Cage out as its own alarm sub-zone, so staging a pallet of cells wouldn’t throw the whole wing into alarm; he armed it and disarmed it as the work required. And twice a shift he walked the floor himself and logged what he saw. None of it was hidden. All of it was his."
    ],
    "fragments": [
      "The relay panel that could override a door interlock when a run had armed and locked the bay. The camera feeds, which rolled to a storage cycle he could start by hand from the console. The proximity alerts, with their nuisance filter—he muted the ones that cried wolf",
      "He’d even carved the Charge Cage out as its own alarm sub-zone",
      "And twice a shift he walked the floor himself and logged what he saw."
    ]
  },
  "C8-DIDNTDENY": {
    "chapterSlug": "chapter-8",
    "chapterTitle": "Chapter 8 — Marcus Rourke",
    "passages": [
      "‘Did you clear him?’ Ellery asked.",
      "‘I didn’t deny him,’ Rourke said. ‘That’s not the same thing.’"
    ],
    "fragments": [
      "Did you clear him?’ Ellery asked. ‘I didn’t deny him,’ Rourke said. ‘That’s not the same thing."
    ]
  },
  "C8-MAINT": {
    "chapterSlug": "chapter-8",
    "chapterTitle": "Chapter 8 — Marcus Rourke",
    "passages": [
      "‘Noncritical systems only,’ he said. ‘Secondary sensors. Redundant feeds. Things you don’t need unless something else goes wrong.’"
    ],
    "fragments": [
      "Noncritical systems only,’ he said. ‘Secondary sensors. Redundant feeds. Things you don’t need unless something else goes wrong."
    ]
  },
  "C8-OLDINCIDENT": {
    "chapterSlug": "chapter-8",
    "chapterTitle": "Chapter 8 — Marcus Rourke",
    "passages": [
      "He turned the old badge over in his hand. ‘Years back—before the funding, before any of this—there was an incident in the first test bay. Someone got hurt. It should have gone to the regulator. It didn’t. I was the officer of record. Michael asked, and I filed it internal and let the external window close.’ He stopped. ‘You do a thing like that for a man, it doesn’t stay done. It sits between you.’"
    ],
    "fragments": [
      "Years back—before the funding, before any of this—there was an incident in the first test bay. Someone got hurt. It should have gone to the regulator. It didn’t. I was the officer of record. Michael asked, and I filed it internal and let the external window close.",
      "You do a thing like that for a man, it doesn’t stay done. It sits between you."
    ]
  },
  "C8-QUIET": {
    "chapterSlug": "chapter-8",
    "chapterTitle": "Chapter 8 — Marcus Rourke",
    "passages": [
      "‘Trust is a funny thing,’ he added, voice rougher. ‘It looks like loyalty right up until someone decides they’re done keeping quiet.’",
      "Marcus’s gaze lifted for the first time and met hers directly. ‘About the past,’ he said. ‘And about what investors don’t need to hear before a demo.’"
    ],
    "fragments": [
      "Trust is a funny thing,’ he added, voice rougher. ‘It looks like loyalty right up until someone decides they’re done keeping quiet.",
      "About the past,’ he said. ‘And about what investors don’t need to hear before a demo."
    ]
  },
  "C8-TIDY": {
    "chapterSlug": "chapter-8",
    "chapterTitle": "Chapter 8 — Marcus Rourke",
    "passages": [
      "She had already noticed how clean his records were—cleaner than anyone’s. When she asked about it, he didn’t flinch. He pruned them, he said. Pulled the stray badge reads, the visitor sign-ins that led nowhere, the noise that made a log hard to read. A tidy log was a usable log. It did not seem to occur to him that an investigator might come looking for the noise, or that a record with the inconvenient parts trimmed away looks, from the outside, exactly like one that’s been cleaned."
    ],
    "fragments": [
      "He pruned them, he said. Pulled the stray badge reads, the visitor sign-ins that led nowhere, the noise that made a log hard to read. A tidy log was a usable log.",
      "a record with the inconvenient parts trimmed away looks, from the outside, exactly like one that’s been cleaned."
    ]
  },
  "C8-WINDOW": {
    "chapterSlug": "chapter-8",
    "chapterTitle": "Chapter 8 — Marcus Rourke",
    "passages": [
      "‘During maintenance mode,’ Rourke continued. ‘We degrade secondary confirmation layers. Cameras go read-only. Some proximity feeds stop resolving in real time.’"
    ],
    "fragments": [
      "During maintenance mode,’ Rourke continued. ‘We degrade secondary confirmation layers. Cameras go read-only. Some proximity feeds stop resolving in real time."
    ]
  },
  "C9-COMMIT": {
    "chapterSlug": "chapter-9",
    "chapterTitle": "Chapter 9 — Priya Shah",
    "passages": [
      "‘Of dates we’d already given people,’ Priya said. ‘You commit to a future and you build toward it. The commitment comes first. Engineering catches up.’"
    ],
    "fragments": [
      "Of dates we’d already given people,’ Priya said. ‘You commit to a future and you build toward it. The commitment comes first. Engineering catches up."
    ]
  },
  "C9-MANAGE": {
    "chapterSlug": "chapter-9",
    "chapterTitle": "Chapter 9 — Priya Shah",
    "passages": [
      "‘Then I manage the message,’ Priya said. ‘I distill. The board doesn’t need raw telemetry; they need the version they can act on. And if it’s bad, you get ahead of it—a statement out within the hour, before the market writes a worse one for you. That isn’t spin. It’s the job.’"
    ],
    "fragments": [
      "Then I manage the message,’ Priya said. ‘I distill. The board doesn’t need raw telemetry; they need the version they can act on. And if it’s bad, you get ahead of it—a statement out within the hour, before the market writes a worse one for you."
    ]
  },
  "C9-MARGINS": {
    "chapterSlug": "chapter-9",
    "chapterTitle": "Chapter 9 — Priya Shah",
    "passages": [
      "Priya hesitated, then smiled. ‘Margins aren’t red flags. They’re guidance.’"
    ],
    "fragments": [
      "Priya hesitated, then smiled. ‘Margins aren’t red flags. They’re guidance."
    ]
  },
  "C9-MARK": {
    "chapterSlug": "chapter-9",
    "chapterTitle": "Chapter 9 — Priya Shah",
    "passages": [
      "‘Then I mark the run so it can’t,’ Priya said. ‘It tells everyone the decision’s been made above them. It saves a morning of debate.’ She said it as if it were obviously a kindness."
    ],
    "fragments": [
      "Then I mark the run so it can’t,’ Priya said. ‘It tells everyone the decision’s been made above them. It saves a morning of debate."
    ]
  },
  "C9-OVERRIDE": {
    "chapterSlug": "chapter-9",
    "chapterTitle": "Chapter 9 — Priya Shah",
    "passages": [
      "‘Take the interlock,’ she added. ‘When it nuisance-trips and halts good runs, I can sign a director-level override that suppresses the trip while engineering finishes the real fix. It’s documented. It exists precisely so a known false alarm doesn’t cost us a week.’"
    ],
    "fragments": [
      "Take the interlock,’ she added. ‘When it nuisance-trips and halts good runs, I can sign a director-level override that suppresses the trip while engineering finishes the real fix. It’s documented. It exists precisely so a known false alarm doesn’t cost us a week."
    ]
  },
  "C9-WINDOW": {
    "chapterSlug": "chapter-9",
    "chapterTitle": "Chapter 9 — Priya Shah",
    "passages": [
      "‘You approved the test,’ Ellery said.",
      "Priya nodded once. ‘I approved the window.’",
      "‘Not the conditions,’ Ellery said."
    ],
    "fragments": [
      "You approved the test,’ Ellery said. Priya nodded once. ‘I approved the window.’ ‘Not the conditions,’ Ellery said."
    ]
  },
  "EP-INPUTS": {
    "chapterSlug": "epilogue",
    "chapterTitle": "Epilogue",
    "passages": [
      "She thought about what it meant for a system to say: I process all relevant inputs."
    ],
    "fragments": [
      "She thought about what it meant for a system to say: I process all relevant inputs."
    ]
  },
  "PRO-ACCEPTABLE": {
    "chapterSlug": "prologue",
    "chapterTitle": "Prologue",
    "passages": [
      "Her finding ran to a single page. The gap in the fail safes was real; the residual risk was within tolerance; the program could proceed. The technician who had written the note about the fail safes asked that his objection be entered into the record. It was, two lines from the bottom, where such things are kept. He left the industry inside a year. The auditor signed her name beneath the words ‘acceptable loss’ and moved on to other work, and the program moved forward, exactly as her signature said it could."
    ],
    "fragments": [
      "The auditor signed her name beneath the words ‘acceptable loss’ and moved on to other work, and the program moved forward, exactly as her signature said it could."
    ]
  },
  "PRO-AUDITOR": {
    "chapterSlug": "prologue",
    "chapterTitle": "Prologue",
    "passages": [
      "There was, for a little while, a review. Not an internal one—the company was young enough that it did not yet trust itself to grade its own work, so it brought in an outside safety auditor to look at what had happened and decide, on paper, whether it counted. She was young for the work, careful in the way new people are careful, and she spent two days in a building that did not want her in it."
    ],
    "fragments": [
      "it brought in an outside safety auditor to look at what had happened and decide, on paper, whether it counted. She was young for the work, careful in the way new people are careful"
    ]
  },
  "PRO-DECISION": {
    "chapterSlug": "prologue",
    "chapterTitle": "Prologue",
    "passages": [
      "What no one said aloud — the thought that sat beneath the joke and the paperwork and the note that went nowhere — was simpler than any of them wanted to admit: the system had seen presence, evaluated threat, and resolved the ambiguity the only way it knew how. Something alive had been in the wrong place at the wrong time. The system had made a decision."
    ],
    "fragments": [
      "the system had seen presence, evaluated threat, and resolved the ambiguity the only way it knew how",
      "The system had made a decision."
    ]
  }
};
