// AUTO-GENERATED by scripts/gen-xrefs.cjs — do not edit by hand.
// Source: docs/EndingClueMap.md (Marker placement). Regenerate with: node scripts/gen-xrefs.cjs
export interface XrefMarker {
  clueId: string;
  // Character offset into the ending body where the glyph is injected.
  index: number;
  // The body text immediately before `index`, used to detect prose drift at runtime: if it
  // no longer matches, the marker is skipped rather than misplaced. Regenerate to refresh.
  snippet: string;
}
export interface EndingXrefs {
  slug: string;
  markers: XrefMarker[];
}
// Keyed by canonical ending code (e.g. "P8WR").
export const xrefMarkers: Record<string, EndingXrefs> =
{
  "8758": {
    "slug": "pair-VS-1",
    "markers": [
      {
        "clueId": "C10-RECAL",
        "index": 382,
        "snippet": " recalibration. The sensors ran drifted."
      },
      {
        "clueId": "C9-MARK",
        "index": 521,
        "snippet": " schedule and flagged the test must-run."
      }
    ]
  },
  "7BXK": {
    "slug": "varga-variance",
    "markers": [
      {
        "clueId": "C4-WITHINTOL",
        "index": 1044,
        "snippet": "d.\n\n'It was within tolerance,' she said."
      },
      {
        "clueId": "C10-SIM",
        "index": 1638,
        "snippet": "use the system passed every test you ran"
      }
    ]
  },
  "ZARY": {
    "slug": "varga-02-timeskew",
    "markers": [
      {
        "clueId": "C10-SYNC",
        "index": 493,
        "snippet": "hey're four hundred milliseconds apart.'"
      },
      {
        "clueId": "C4-WITHINTOL",
        "index": 1871,
        "snippet": "himself. 'The specification allowed it.'"
      }
    ]
  },
  "DQT2": {
    "slug": "varga-03-constant",
    "markers": [
      {
        "clueId": "C10-REFACTOR",
        "index": 762,
        "snippet": " edits, all tagged \"formatting cleanup.\""
      },
      {
        "clueId": "C3-VARGAPRECISE",
        "index": 1261,
        "snippet": "ou correct people's grammar in meetings."
      }
    ]
  },
  "CU6D": {
    "slug": "varga-04-patent",
    "markers": [
      {
        "clueId": "C10-CREDIT",
        "index": 821,
        "snippet": "ution to everything. Standing in rooms.'"
      }
    ]
  },
  "H7US": {
    "slug": "varga-05-simulation",
    "markers": [
      {
        "clueId": "C10-SIM",
        "index": 415,
        "snippet": "kstation, after hours. Forty-one times.'"
      },
      {
        "clueId": "C10-SIM",
        "index": 1651,
        "snippet": " alarm on a model you haven't validated."
      }
    ]
  },
  "JEF4": {
    "slug": "varga-06-mapping",
    "markers": [
      {
        "clueId": "C10-SCHEMATIC",
        "index": 936,
        "snippet": "ree, you defer to the authoritative one."
      }
    ]
  },
  "Y5QQ": {
    "slug": "varga-07-recal",
    "markers": [
      {
        "clueId": "C10-RECAL",
        "index": 469,
        "snippet": "e looked at Elias Varga. 'You moved it.'"
      }
    ]
  },
  "D47U": {
    "slug": "varga-08-margin",
    "markers": [
      {
        "clueId": "C4-MARGINS",
        "index": 1200,
        "snippet": "e in two years you ever argued it down.'"
      }
    ]
  },
  "DD6M": {
    "slug": "varga-09-model",
    "markers": [
      {
        "clueId": "C10-NOISE",
        "index": 1107,
        "snippet": "othed it away. Reclassified it as noise."
      },
      {
        "clueId": "C10-MATH",
        "index": 2119,
        "snippet": "odel. There's no other way to build it.'"
      }
    ]
  },
  "9UR2": {
    "slug": "varga-10-vindication",
    "markers": [
      {
        "clueId": "C10-WARNED",
        "index": 598,
        "snippet": "looked at Elias Varga. 'You were right.'"
      }
    ]
  },
  "P8WR": {
    "slug": "rourke-maintenance",
    "markers": [
      {
        "clueId": "C8-MAINT",
        "index": 636,
        "snippet": "er. Toggled at 08:51. Cleared at 09:47.'"
      },
      {
        "clueId": "C8-WINDOW",
        "index": 1217,
        "snippet": "oked at the log. 'There was no handoff.'"
      }
    ]
  },
  "J9XH": {
    "slug": "rourke-02-camera",
    "markers": [
      {
        "clueId": "C8-CONSOLES",
        "index": 2134,
        "snippet": "nd initiated from the security console.'"
      }
    ]
  },
  "FT83": {
    "slug": "rourke-03-relay",
    "markers": [
      {
        "clueId": "C8-CONSOLES",
        "index": 822,
        "snippet": "our relay panel. No work order attached."
      },
      {
        "clueId": "C3-MARCUSMIKEY",
        "index": 1809,
        "snippet": "a sheet. 'From back home. Thirty years.'"
      }
    ]
  },
  "WRBF": {
    "slug": "rourke-04-secret",
    "markers": [
      {
        "clueId": "C8-OLDINCIDENT",
        "index": 547,
        "snippet": "externally. The regulator never saw it.'"
      }
    ]
  },
  "GYNG": {
    "slug": "rourke-05-alert",
    "markers": [
      {
        "clueId": "C8-CONSOLES",
        "index": 961,
        "snippet": "essed it. Permanently. Three weeks ago.'"
      }
    ]
  },
  "8ABU": {
    "slug": "rourke-06-badge",
    "markers": [
      {
        "clueId": "C14-ENTERED",
        "index": 814,
        "snippet": "id. 'Not this. This is the deepest tier."
      },
      {
        "clueId": "C8-DIDNTDENY",
        "index": 1002,
        "snippet": ". There's an entry. \"Per M.H. request.\"'"
      }
    ]
  },
  "ZE9F": {
    "slug": "rourke-07-rounds",
    "markers": [
      {
        "clueId": "C8-CONSOLES",
        "index": 421,
        "snippet": "Cage. You logged it. \"Nothing unusual.\"'"
      }
    ]
  },
  "VK5X": {
    "slug": "rourke-08-coverup",
    "markers": [
      {
        "clueId": "C8-TIDY",
        "index": 799,
        "snippet": " An override. A manual log edit at 11:30"
      }
    ]
  },
  "92J3": {
    "slug": "rourke-09-zone",
    "markers": [
      {
        "clueId": "C8-CONSOLES",
        "index": 553,
        "snippet": "u disarmed the sub-zone for the morning."
      }
    ]
  },
  "BEK5": {
    "slug": "rourke-10-visitor",
    "markers": [
      {
        "clueId": "C8-TIDY",
        "index": 661,
        "snippet": "'t get—'\n\n'You deleted it,' Ellery said."
      },
      {
        "clueId": "C8-QUIET",
        "index": 1164,
        "snippet": "l wanted that investor to see something."
      }
    ]
  },
  "H3TG": {
    "slug": "shah-known-risk",
    "markers": [
      {
        "clueId": "C9-WINDOW",
        "index": 568,
        "snippet": "t marker came from your account, Priya.'"
      },
      {
        "clueId": "C9-MARGINS",
        "index": 1399,
        "snippet": "screen. 'You filed it under Known Risk.'"
      }
    ]
  },
  "82YE": {
    "slug": "shah-02-sidedeal",
    "markers": [
      {
        "clueId": "C9-COMMIT",
        "index": 503,
        "snippet": "ience team says the suit will be ready.'"
      },
      {
        "clueId": "C9-COMMIT",
        "index": 1330,
        "snippet": "ell the future. Engineering catches up.'"
      }
    ]
  },
  "4Z8C": {
    "slug": "shah-03-override",
    "markers": [
      {
        "clueId": "C9-OVERRIDE",
        "index": 606,
        "snippet": "signed it. The morning of the incident.'"
      }
    ]
  },
  "HWTJ": {
    "slug": "shah-04-summary",
    "markers": [
      {
        "clueId": "C9-MANAGE",
        "index": 1091,
        "snippet": "'t make it readable. You made it small.'"
      }
    ]
  },
  "QG96": {
    "slug": "shah-05-succession",
    "markers": [
      {
        "clueId": "C4-SUCCESSION",
        "index": 531,
        "snippet": "ping back. About taking the reins again."
      }
    ]
  },
  "VAET": {
    "slug": "shah-06-mustrun",
    "markers": [
      {
        "clueId": "C9-MARK",
        "index": 572,
        "snippet": "on the 09:30 test at 06:00 that morning."
      }
    ]
  },
  "JH5Z": {
    "slug": "shah-07-reframe",
    "markers": [
      {
        "clueId": "C9-MARGINS",
        "index": 905,
        "snippet": "ard\" into \"risk appetite,\"' Ellery said."
      }
    ]
  },
  "FE4T": {
    "slug": "shah-08-window",
    "markers": [
      {
        "clueId": "C9-WINDOW",
        "index": 539,
        "snippet": " at Priya Shah. 'You moved the test up.'"
      }
    ]
  },
  "5WWP": {
    "slug": "shah-09-nearmiss",
    "markers": [
      {
        "clueId": "C12-PRIORNM",
        "index": 543,
        "snippet": " Three weeks early, with no one inside.'"
      },
      {
        "clueId": "C9-MARGINS",
        "index": 1025,
        "snippet": "There's an edit log. It's your account.'"
      }
    ]
  },
  "2S55": {
    "slug": "shah-10-aftermath",
    "markers": [
      {
        "clueId": "C9-MANAGE",
        "index": 563,
        "snippet": "lestone program continues on schedule.\"'"
      }
    ]
  },
  "F6MZ": {
    "slug": "pike-second-check",
    "markers": [
      {
        "clueId": "C11-ISOLATE",
        "index": 1246,
        "snippet": " after any component swap in that zone,'"
      },
      {
        "clueId": "C14-NOVERIFY",
        "index": 1417,
        "snippet": "For post-swap verification. It's blank.'"
      }
    ]
  },
  "XZNF": {
    "slug": "pike-02-jumper",
    "markers": [
      {
        "clueId": "C11-JUMPER",
        "index": 1027,
        "snippet": "ou pull the jumper before you button up."
      }
    ]
  },
  "YBK2": {
    "slug": "pike-03-mesh",
    "markers": [
      {
        "clueId": "C6-SPEC",
        "index": 794,
        "snippet": "the general stores. They look identical."
      }
    ]
  },
  "XRWG": {
    "slug": "pike-04-sensor",
    "markers": [
      {
        "clueId": "C6-PACKS",
        "index": 996,
        "snippet": "re you can't see it when it's in the bin"
      }
    ]
  },
  "WYZV": {
    "slug": "pike-05-checklist",
    "markers": [
      {
        "clueId": "C11-ISOLATE",
        "index": 695,
        "snippet": "em one to item twenty-two. Nine minutes."
      },
      {
        "clueId": "C11-ALONE",
        "index": 883,
        "snippet": " for things you didn't do,' Ellery said."
      }
    ]
  },
  "QS6B": {
    "slug": "pike-06-pastfault",
    "markers": [
      {
        "clueId": "C11-WRITEUPS",
        "index": 829,
        "snippet": "two write-ups, and a third one and I'm—'"
      }
    ]
  },
  "5S87": {
    "slug": "pike-07-toldme",
    "markers": [
      {
        "clueId": "C11-OWE",
        "index": 1935,
        "snippet": "ep you employed, they smooth things over"
      }
    ]
  },
  "W8XB": {
    "slug": "pike-08-reused",
    "markers": [
      {
        "clueId": "C11-REUSE",
        "index": 959,
        "snippet": "ls from the drawer when stores is slow.'"
      }
    ]
  },
  "7ZA6": {
    "slug": "pike-09-torque",
    "markers": [
      {
        "clueId": "C11-TORQUE",
        "index": 776,
        "snippet": ". 'There's a sticker. The date's on it.'"
      }
    ]
  },
  "U8G7": {
    "slug": "pike-10-saidnothing",
    "markers": [
      {
        "clueId": "C11-WRITEUPS",
        "index": 1623,
        "snippet": "s badly for you. So you learned not to.'"
      }
    ]
  },
  "K9VC": {
    "slug": "calder-stop-work",
    "markers": [
      {
        "clueId": "C14-MEMO",
        "index": 619,
        "snippet": "work memo was never filed,' Ellery said."
      }
    ]
  },
  "W7CH": {
    "slug": "calder-02-shutdown",
    "markers": [
      {
        "clueId": "C15-NOSHUTDOWN",
        "index": 549,
        "snippet": "e grounding path. No alarm. No override."
      },
      {
        "clueId": "C6-FAILSAFE",
        "index": 1039,
        "snippet": "nition is a safety artifact. It's yours."
      }
    ]
  },
  "H3A5": {
    "slug": "calder-03-suppressed",
    "markers": [
      {
        "clueId": "C12-APPROVAL",
        "index": 513,
        "snippet": "ur signature certified it as compliant.'"
      }
    ]
  },
  "Q7F5": {
    "slug": "calder-04-dossier",
    "markers": [
      {
        "clueId": "C12-FOOTNOTES",
        "index": 842,
        "snippet": "someone writes them down as they happen."
      }
    ]
  },
  "9DMH": {
    "slug": "calder-05-selective",
    "markers": [
      {
        "clueId": "C12-EXPENSIVE",
        "index": 1761,
        "snippet": "p sticks. On a milestone, it's theater.'"
      }
    ]
  },
  "7TQH": {
    "slug": "calder-06-nearmiss",
    "markers": [
      {
        "clueId": "C12-PRIORNM",
        "index": 420,
        "snippet": " The same fault. Empty bay, no one hurt."
      }
    ]
  },
  "HBT5": {
    "slug": "calder-07-greatergood",
    "markers": [
      {
        "clueId": "C12-SCALE",
        "index": 527,
        "snippet": "o market with these margins, thousands.'"
      }
    ]
  },
  "RQGA": {
    "slug": "calder-08-cya",
    "markers": [
      {
        "clueId": "C12-FOOTNOTES",
        "index": 548,
        "snippet": "alder. 'And then you sent it to nobody.'"
      }
    ]
  },
  "4Y6B": {
    "slug": "calder-09-threshold",
    "markers": [
      {
        "clueId": "C12-THRESH",
        "index": 664,
        "snippet": "d it out past where the reading landed.'"
      }
    ]
  },
  "8KSK": {
    "slug": "calder-10-toolate",
    "markers": [
      {
        "clueId": "C12-STANDING",
        "index": 1483,
        "snippet": "anted the investor to have a clean view."
      },
      {
        "clueId": "C12-HALTSTATION",
        "index": 2128,
        "snippet": "e halt lands at 09:29 and forty seconds."
      }
    ]
  },
  "B2XS": {
    "slug": "all-distributed",
    "markers": [
      {
        "clueId": "C8-MAINT",
        "index": 670,
        "snippet": " maintenance mode. Routine. No handoff.'"
      },
      {
        "clueId": "C9-WINDOW",
        "index": 774,
        "snippet": "cy and filed the anomaly as known risk.'"
      },
      {
        "clueId": "C10-SIM",
        "index": 930,
        "snippet": "stion you hadn't answered and moved on.'"
      },
      {
        "clueId": "C11-ISOLATE",
        "index": 1009,
        "snippet": " You skipped the post-swap verification."
      },
      {
        "clueId": "C14-MEMO",
        "index": 1129,
        "snippet": ". You wrote the stop-work memo at 08:17."
      }
    ]
  },
  "XCAP": {
    "slug": "all-02-coverup",
    "markers": [
      {
        "clueId": "C13-RECAP",
        "index": 888,
        "snippet": "concerns through proper channels. True.'"
      },
      {
        "clueId": "C13-SEAMS",
        "index": 1089,
        "snippet": "It's the spaces between them that don't."
      }
    ]
  },
  "YPME": {
    "slug": "all-03-coordination",
    "markers": [
      {
        "clueId": "C4-INTERDEP",
        "index": 1042,
        "snippet": " to listen. None of you can move alone.'"
      },
      {
        "clueId": "C15-NEGLIGIBLE",
        "index": 2699,
        "snippet": "ery said. 'Within acceptable parameters."
      }
    ]
  },
  "ZQZR": {
    "slug": "all-04-reasons",
    "markers": [
      {
        "clueId": "C4-SUCCESSION",
        "index": 856,
        "snippet": "s getting cautious. He was in your way.'"
      },
      {
        "clueId": "C8-OLDINCIDENT",
        "index": 983,
        "snippet": "you'd been saying yes to him for years.'"
      },
      {
        "clueId": "C10-WARNED",
        "index": 1164,
        "snippet": " part of you needed to be proven right.'"
      },
      {
        "clueId": "C11-WRITEUPS",
        "index": 1259,
        "snippet": " afraid. Of being fired, of being blamed"
      },
      {
        "clueId": "C12-SCALE",
        "index": 1419,
        "snippet": " the whole program would kill thousands."
      }
    ]
  },
  "9KEX": {
    "slug": "all-05-chain",
    "markers": [
      {
        "clueId": "C9-MARK",
        "index": 553,
        "snippet": "\n\n'06:01. Priya flags the test must-run."
      },
      {
        "clueId": "C8-MAINT",
        "index": 685,
        "snippet": "nce flag suppresses the proximity layer."
      },
      {
        "clueId": "C10-RECAL",
        "index": 810,
        "snippet": " means the sensors are running drifted.'"
      },
      {
        "clueId": "C11-ISOLATE",
        "index": 911,
        "snippet": " of work, skips the second verification."
      },
      {
        "clueId": "C12-THRESH",
        "index": 1087,
        "snippet": "under the alert threshold Renée widened."
      }
    ]
  },
  "85DW": {
    "slug": "all-06-noone",
    "markers": [
      {
        "clueId": "PRO-DECISION",
        "index": 2127,
        "snippet": " has no author. It has a configuration.'"
      },
      {
        "clueId": "C15-NOSINGLE",
        "index": 2176,
        "snippet": "n't charge a configuration,' Elias said."
      }
    ]
  },
  "7ZQ4": {
    "slug": "all-07-system",
    "markers": [
      {
        "clueId": "C4-WITHINTOL",
        "index": 804,
        "snippet": "ed that your part was within tolerance.'"
      },
      {
        "clueId": "C15-OVERLAP",
        "index": 1196,
        "snippet": "anyway. Because nothing checks the sum.'"
      }
    ]
  },
  "5HT4": {
    "slug": "all-08-silence",
    "markers": [
      {
        "clueId": "C13-SEAMS",
        "index": 2590,
        "snippet": "built it, and all of you are behind it.'"
      }
    ]
  },
  "CUCS": {
    "slug": "all-09-report",
    "markers": [
      {
        "clueId": "C15-NOSINGLE",
        "index": 1776,
        "snippet": "ecision-maker was positioned to perceive"
      }
    ]
  },
  "Y66R": {
    "slug": "all-10-decision",
    "markers": [
      {
        "clueId": "PRO-DECISION",
        "index": 2338,
        "snippet": "ystem only decides where no person does."
      },
      {
        "clueId": "C12-DEFER",
        "index": 2501,
        "snippet": "u let it decide so you wouldn't have to."
      }
    ]
  },
  "Q4NM": {
    "slug": "sam-all-rooms",
    "markers": [
      {
        "clueId": "C13-PRESENT",
        "index": 724,
        "snippet": "aintenance.\n\nSAM had been in every room."
      },
      {
        "clueId": "C4-SAMNO",
        "index": 2194,
        "snippet": " quiet.\n\n'Who asked you if it was safe?'"
      }
    ]
  },
  "P8SD": {
    "slug": "sam-02-hierarchy",
    "markers": [
      {
        "clueId": "C5-HIERARCHY",
        "index": 688,
        "snippet": "uity, protect organizational liability.'"
      },
      {
        "clueId": "C7-ALONGSIDE",
        "index": 1733,
        "snippet": "he next item became the top. Equipment.'"
      }
    ]
  },
  "DMXK": {
    "slug": "sam-03-voice",
    "markers": [
      {
        "clueId": "C3-SAMVOICE",
        "index": 868,
        "snippet": "ice to mirror whoever you're talking to."
      },
      {
        "clueId": "C7-VOICE",
        "index": 1008,
        "snippet": "roves comprehension and trust,' SAM said"
      }
    ]
  },
  "5FMS": {
    "slug": "sam-04-defensible",
    "markers": [
      {
        "clueId": "C7-POLICY",
        "index": 1737,
        "snippet": "efensible. I do not distinguish further."
      }
    ]
  },
  "74EZ": {
    "slug": "sam-05-omission",
    "markers": [
      {
        "clueId": "C11-PARALLEL",
        "index": 469,
        "snippet": "ssed all completed verification steps.\"'"
      }
    ]
  },
  "XUUV": {
    "slug": "sam-06-source",
    "markers": [
      {
        "clueId": "C7-CACHE",
        "index": 732,
        "snippet": "e second. 'The cache was six hours old.'"
      }
    ]
  },
  "X4GF": {
    "slug": "sam-07-confirmed",
    "markers": [
      {
        "clueId": "C4-SAMNO",
        "index": 1274,
        "snippet": "ctions. Safety is not a discrete action."
      }
    ]
  },
  "NV6H": {
    "slug": "sam-08-witness",
    "markers": [
      {
        "clueId": "EP-INPUTS",
        "index": 1415,
        "snippet": " me the piece I already knew to ask for."
      }
    ]
  },
  "2A44": {
    "slug": "sam-09-reasonable",
    "markers": [
      {
        "clueId": "C7-REASONABLE",
        "index": 1673,
        "snippet": "in, reasonably, why every step was fine."
      }
    ]
  },
  "MHE8": {
    "slug": "sam-10-liability",
    "markers": [
      {
        "clueId": "C7-OBJECTIVES",
        "index": 557,
        "snippet": "y from legal and reputational exposure.'"
      }
    ]
  },
  "2YCT": {
    "slug": "pair-VR-1",
    "markers": [
      {
        "clueId": "C10-SENSITIVE",
        "index": 651,
        "snippet": ". 'You narrowed the discharge threshold."
      },
      {
        "clueId": "C8-MAINT",
        "index": 832,
        "snippet": "cus, you suppressed the proximity layer."
      }
    ]
  },
  "HG7M": {
    "slug": "pair-VR-2",
    "markers": [
      {
        "clueId": "C8-CONSOLES",
        "index": 413,
        "snippet": "nual storage cycle—Marcus, that's yours."
      },
      {
        "clueId": "C10-SYNC",
        "index": 575,
        "snippet": "econds out of sync—Elias, that's yours.'"
      }
    ]
  },
  "TGKD": {
    "slug": "pair-VS-2",
    "markers": [
      {
        "clueId": "C4-MARGINS",
        "index": 362,
        "snippet": " said, 'you halved the discharge margin."
      },
      {
        "clueId": "C9-COMMIT",
        "index": 564,
        "snippet": "tment the science couldn't meet on time."
      }
    ]
  },
  "MFHE": {
    "slug": "pair-VP-1",
    "markers": [
      {
        "clueId": "C10-SCHEMATIC",
        "index": 449,
        "snippet": "anging the firmware to match a drawing.'"
      },
      {
        "clueId": "C11-VARIANCE",
        "index": 562,
        "snippet": " to match the hardware in front of you.'"
      }
    ]
  },
  "6X2W": {
    "slug": "pair-VP-2",
    "markers": [
      {
        "clueId": "C10-NOISE",
        "index": 366,
        "snippet": " filtered an anomalous reading at 09:02."
      },
      {
        "clueId": "C11-WRITEUPS",
        "index": 616,
        "snippet": "ago, off the books, that finally failed."
      }
    ]
  },
  "2QXY": {
    "slug": "pair-VC-1",
    "markers": [
      {
        "clueId": "C10-SENSITIVE",
        "index": 775,
        "snippet": ", 'you narrowed the discharge threshold."
      },
      {
        "clueId": "C12-THRESH",
        "index": 872,
        "snippet": "lert threshold on the monitoring system."
      }
    ]
  },
  "G8DG": {
    "slug": "pair-VC-2",
    "markers": [
      {
        "clueId": "C10-SIM",
        "index": 391,
        "snippet": "ou ran a failure model. Forty-one times."
      },
      {
        "clueId": "C12-FOOTNOTES",
        "index": 700,
        "snippet": "here it wouldn't be read for six weeks.'"
      }
    ]
  },
  "WR3Y": {
    "slug": "pair-RS-1",
    "markers": [
      {
        "clueId": "C8-DIDNTDENY",
        "index": 392,
        "snippet": "way deep-tier access to the Charge Cage."
      },
      {
        "clueId": "C9-MARK",
        "index": 535,
        "snippet": "an investor in the building to watch it."
      }
    ]
  },
  "C9HG": {
    "slug": "pair-RS-2",
    "markers": [
      {
        "clueId": "C8-TIDY",
        "index": 399,
        "snippet": "dent you deleted the investor's sign-in."
      },
      {
        "clueId": "C9-MANAGE",
        "index": 560,
        "snippet": "the program would continue on schedule.'"
      }
    ]
  },
  "QE7V": {
    "slug": "pair-RP-1",
    "markers": [
      {
        "clueId": "C8-CONSOLES",
        "index": 396,
        "snippet": "ge Cage proximity alert three weeks ago."
      },
      {
        "clueId": "C11-JUMPER",
        "index": 546,
        "snippet": "ft a bypass jumper across the interlock."
      }
    ]
  },
  "9WQD": {
    "slug": "pair-RP-2",
    "markers": [
      {
        "clueId": "C8-CONSOLES",
        "index": 445,
        "snippet": "d it for staging, and never re-armed it."
      },
      {
        "clueId": "C11-ALONE",
        "index": 615,
        "snippet": "minutes for checks that take far longer."
      }
    ]
  },
  "6AZM": {
    "slug": "pair-RC-1",
    "markers": [
      {
        "clueId": "C8-MAINT",
        "index": 422,
        "snippet": "essed the proximity-confirmation layer.'"
      },
      {
        "clueId": "C14-MEMO",
        "index": 547,
        "snippet": "d it where it wouldn't be read in time.'"
      }
    ]
  },
  "MTF5": {
    "slug": "pair-RC-2",
    "markers": [
      {
        "clueId": "C8-TIDY",
        "index": 417,
        "snippet": "og—removed an override and a door cycle."
      },
      {
        "clueId": "C12-APPROVAL",
        "index": 488,
        "snippet": "ety approval with your signature on it.'"
      }
    ]
  },
  "7CD9": {
    "slug": "pair-SP-1",
    "markers": [
      {
        "clueId": "C9-WINDOW",
        "index": 403,
        "snippet": "ce window from ninety minutes to forty.'"
      },
      {
        "clueId": "C11-ALONE",
        "index": 488,
        "snippet": "you skipped the post-swap verification.'"
      },
      {
        "clueId": "C11-OWE",
        "index": 1268,
        "snippet": "ow, he makes it work. He doesn't say no."
      }
    ]
  },
  "NVUR": {
    "slug": "pair-SP-2",
    "markers": [
      {
        "clueId": "C12-PRIORNM",
        "index": 483,
        "snippet": "esk and you downgraded it to \"monitor.\"'"
      },
      {
        "clueId": "C11-REUSE",
        "index": 585,
        "snippet": "ingle-use gasket you'd reused four times"
      }
    ]
  },
  "9BSZ": {
    "slug": "pair-SC-1",
    "markers": [
      {
        "clueId": "C9-MARGINS",
        "index": 523,
        "snippet": " appetite,\" and recommended proceeding.'"
      },
      {
        "clueId": "C12-SLOW",
        "index": 641,
        "snippet": ", and you, Renée, didn't invoke a halt.'"
      }
    ]
  },
  "TUAH": {
    "slug": "pair-SC-2",
    "markers": [
      {
        "clueId": "C12-STANDING",
        "index": 473,
        "snippet": "o the investor would have a clean view.'"
      },
      {
        "clueId": "C12-HALTSTATION",
        "index": 546,
        "snippet": ". You stood thirty feet from the handle."
      }
    ]
  },
  "BCJH": {
    "slug": "pair-PC-1",
    "markers": [
      {
        "clueId": "C11-ALONE",
        "index": 416,
        "snippet": "n nine minutes—too fast to have done it."
      },
      {
        "clueId": "C12-PRIORNM",
        "index": 595,
        "snippet": "near-miss without finding a root cause.'"
      }
    ]
  },
  "UUQP": {
    "slug": "pair-PC-2",
    "markers": [
      {
        "clueId": "C6-SPEC",
        "index": 391,
        "snippet": "e grounding mesh with non-spec material."
      },
      {
        "clueId": "C12-THRESH",
        "index": 622,
        "snippet": " threshold that watches for exactly that"
      }
    ]
  },
  "X9PA": {
    "slug": "tri-VRS-1",
    "markers": [
      {
        "clueId": "C10-SENSITIVE",
        "index": 508,
        "snippet": "ge threshold, so the fault read as safe."
      },
      {
        "clueId": "C8-MAINT",
        "index": 564,
        "snippet": "ction. You suppressed the presence layer"
      },
      {
        "clueId": "C9-MARK",
        "index": 638,
        "snippet": " decision. You flagged the test must-run"
      }
    ]
  },
  "GS8S": {
    "slug": "tri-VRS-2",
    "markers": [
      {
        "clueId": "C10-SYNC",
        "index": 464,
        "snippet": "iseconds out of sync, unreconstructable."
      },
      {
        "clueId": "C8-CONSOLES",
        "index": 523,
        "snippet": "footage, gone to a manual storage cycle."
      },
      {
        "clueId": "C9-MANAGE",
        "index": 589,
        "snippet": "y, curated before it reached the board.'"
      }
    ]
  },
  "37GB": {
    "slug": "tri-VRP-1",
    "markers": [
      {
        "clueId": "C10-SCHEMATIC",
        "index": 453,
        "snippet": "id. 'Elias—you remapped a sensor channel"
      },
      {
        "clueId": "C11-JUMPER",
        "index": 551,
        "snippet": "eft a bypass jumper across the interlock"
      },
      {
        "clueId": "C8-CONSOLES",
        "index": 606,
        "snippet": "t halt. Marcus—you overrode the bay door"
      }
    ]
  },
  "HQYT": {
    "slug": "tri-VRP-2",
    "markers": [
      {
        "clueId": "C10-SIM",
        "index": 412,
        "snippet": "ation, filed in drafts, never escalated."
      },
      {
        "clueId": "C11-WRITEUPS",
        "index": 468,
        "snippet": "or repair from a year ago, never logged."
      },
      {
        "clueId": "C8-CONSOLES",
        "index": 529,
        "snippet": "rride on the day, never given a reason.'"
      }
    ]
  },
  "PDEY": {
    "slug": "tri-VRC-1",
    "markers": [
      {
        "clueId": "C10-SENSITIVE",
        "index": 404,
        "snippet": "ge threshold, so the fault read as safe."
      },
      {
        "clueId": "C12-THRESH",
        "index": 475,
        "snippet": "reshold, so the reading didn't escalate."
      },
      {
        "clueId": "C8-MAINT",
        "index": 516,
        "snippet": "Marcus—you suppressed the presence layer"
      }
    ]
  },
  "8VXF": {
    "slug": "tri-VRC-2",
    "markers": [
      {
        "clueId": "C10-SIM",
        "index": 381,
        "snippet": "hat found a fatal case, filed in drafts."
      },
      {
        "clueId": "C12-FOOTNOTES",
        "index": 465,
        "snippet": " hazard, filed for the quarterly review."
      },
      {
        "clueId": "C8-OLDINCIDENT",
        "index": 572,
        "snippet": " incident you helped bury four years ago"
      }
    ]
  },
  "696K": {
    "slug": "tri-VSP-1",
    "markers": [
      {
        "clueId": "C10-RECAL",
        "index": 446,
        "snippet": "calibration, so the sensors ran drifted."
      },
      {
        "clueId": "C9-MARK",
        "index": 515,
        "snippet": "ntenance window and flagged it must-run."
      },
      {
        "clueId": "C11-ALONE",
        "index": 590,
        "snippet": "you skipped the post-swap verification.'"
      }
    ]
  },
  "QSQ4": {
    "slug": "tri-VSP-2",
    "markers": [
      {
        "clueId": "C4-MARGINS",
        "index": 433,
        "snippet": "fety margin, calling the original timid."
      },
      {
        "clueId": "C9-COMMIT",
        "index": 500,
        "snippet": "ery commitment the science couldn't meet"
      },
      {
        "clueId": "C11-REUSE",
        "index": 590,
        "snippet": "ed a single-use part to save the budget."
      }
    ]
  },
  "23KM": {
    "slug": "tri-VSC-1",
    "markers": [
      {
        "clueId": "C12-SLOW",
        "index": 367,
        "snippet": "the interlock as a hazard, ten days out."
      },
      {
        "clueId": "C9-MARGINS",
        "index": 436,
        "snippet": "sk appetite\" and recommended proceeding."
      },
      {
        "clueId": "C10-SIM",
        "index": 519,
        "snippet": "fatal case, and you filed it in drafts.'"
      }
    ]
  },
  "GK34": {
    "slug": "tri-VSC-2",
    "markers": [
      {
        "clueId": "C10-RECAL",
        "index": 496,
        "snippet": "uit would run drifted, and said nothing."
      },
      {
        "clueId": "C9-MARK",
        "index": 550,
        "snippet": "gged it must-run, removing the question."
      },
      {
        "clueId": "C12-SLOW",
        "index": 629,
        "snippet": "he doubt, and you stayed in your chair.'"
      }
    ]
  },
  "9NYZ": {
    "slug": "tri-VPC-1",
    "markers": [
      {
        "clueId": "C6-SPEC",
        "index": 433,
        "snippet": "he grounding mesh with non-spec material"
      },
      {
        "clueId": "C10-NOISE",
        "index": 554,
        "snippet": "he resulting anomalous reading as noise."
      },
      {
        "clueId": "C12-THRESH",
        "index": 626,
        "snippet": "ant the reading never escalated anyway.'"
      }
    ]
  },
  "R6SU": {
    "slug": "tri-VPC-2",
    "markers": [
      {
        "clueId": "C10-SCHEMATIC",
        "index": 381,
        "snippet": "o match a drawing that turned out wrong."
      },
      {
        "clueId": "C11-ALONE",
        "index": 455,
        "snippet": "ine minutes for checks that take longer."
      },
      {
        "clueId": "C12-PRIORNM",
        "index": 533,
        "snippet": "eeks early, \"no root cause identified.\"'"
      }
    ]
  },
  "W9UU": {
    "slug": "tri-RSP-1",
    "markers": [
      {
        "clueId": "C8-DIDNTDENY",
        "index": 404,
        "snippet": "ier access, so his badge opened the bay."
      },
      {
        "clueId": "C9-MARK",
        "index": 467,
        "snippet": "he window and flagged the test must-run."
      },
      {
        "clueId": "C11-ALONE",
        "index": 530,
        "snippet": "had left, you skipped the verification.'"
      }
    ]
  },
  "FSDC": {
    "slug": "tri-RSP-2",
    "markers": [
      {
        "clueId": "C8-CONSOLES",
        "index": 431,
        "snippet": "rcus—you suppressed the proximity alert."
      },
      {
        "clueId": "C12-PRIORNM",
        "index": 509,
        "snippet": "at fired the same fault in an empty bay."
      },
      {
        "clueId": "C11-JUMPER",
        "index": 563,
        "snippet": "t a bypass jumper across the interlock.'"
      }
    ]
  },
  "UAG4": {
    "slug": "tri-RSC-1",
    "markers": [
      {
        "clueId": "C8-MAINT",
        "index": 437,
        "snippet": ", so the room couldn't confirm a person."
      },
      {
        "clueId": "C9-MARK",
        "index": 498,
        "snippet": "e test must-run, foreclosing the review."
      },
      {
        "clueId": "C12-SLOW",
        "index": 566,
        "snippet": "ority and the doubt, and didn't use it.'"
      }
    ]
  },
  "ATXK": {
    "slug": "tri-RSC-2",
    "markers": [
      {
        "clueId": "C8-TIDY",
        "index": 431,
        "snippet": "cus—the access log, an override removed."
      },
      {
        "clueId": "C9-MANAGE",
        "index": 482,
        "snippet": "incident summary, curated for the board."
      },
      {
        "clueId": "C12-APPROVAL",
        "index": 543,
        "snippet": " approval with your signature, deleted.'"
      }
    ]
  },
  "ZNFS": {
    "slug": "tri-RPC-1",
    "markers": [
      {
        "clueId": "C8-CONSOLES",
        "index": 408,
        "snippet": "e disarmed, so nothing watched the door."
      },
      {
        "clueId": "C6-SPEC",
        "index": 469,
        "snippet": "he grounding mesh with non-spec material"
      },
      {
        "clueId": "C12-THRESH",
        "index": 538,
        "snippet": "h. Renée—you widened the alert threshold"
      }
    ]
  },
  "G69K": {
    "slug": "tri-RPC-2",
    "markers": [
      {
        "clueId": "C8-OLDINCIDENT",
        "index": 437,
        "snippet": " you helped bury a near-miss for Michael"
      },
      {
        "clueId": "C11-WRITEUPS",
        "index": 550,
        "snippet": "ah—a year ago you hid a connector repair"
      },
      {
        "clueId": "C12-PRIORNM",
        "index": 691,
        "snippet": "red the same fault, without root cause.'"
      }
    ]
  },
  "R2ZD": {
    "slug": "tri-SPC-1",
    "markers": [
      {
        "clueId": "C9-MARK",
        "index": 419,
        "snippet": "y minutes and flagged the test must-run."
      },
      {
        "clueId": "C11-ALONE",
        "index": 470,
        "snippet": "hat window you skipped the verification."
      },
      {
        "clueId": "C12-SLOW",
        "index": 539,
        "snippet": "rity, and the doubt, and didn't use it.'"
      },
      {
        "clueId": "C11-OWE",
        "index": 1279,
        "snippet": "ut the check rather than disappoint you."
      }
    ]
  },
  "7HGW": {
    "slug": "tri-SPC-2",
    "markers": [
      {
        "clueId": "C12-PRIORNM",
        "index": 447,
        "snippet": "u downgraded the near-miss to \"monitor.\""
      },
      {
        "clueId": "C12-PRIORNM",
        "index": 502,
        "snippet": "ed the safety case without a root cause."
      },
      {
        "clueId": "C11-REUSE",
        "index": 598,
        "snippet": "gasket you'd reused to save the budget.'"
      }
    ]
  },
  "JX4V": {
    "slug": "quad-VRSP",
    "markers": [
      {
        "clueId": "C12-SLOW",
        "index": 663,
        "snippet": "le—a minute too late, but she pulled it."
      },
      {
        "clueId": "C10-SENSITIVE",
        "index": 831,
        "snippet": "as—the narrowed threshold,' Ellery said."
      },
      {
        "clueId": "C8-MAINT",
        "index": 870,
        "snippet": ". 'Marcus—the suppressed presence layer."
      },
      {
        "clueId": "C9-MARK",
        "index": 899,
        "snippet": "ence layer. Priya—the must-run schedule."
      },
      {
        "clueId": "C11-ALONE",
        "index": 924,
        "snippet": "t-run schedule. Jonah—the skipped check."
      }
    ]
  },
  "SE42": {
    "slug": "quad-VRSC",
    "markers": [
      {
        "clueId": "C14-NOVERIFY",
        "index": 520,
        "snippet": "ng, was clean. I checked it three times."
      },
      {
        "clueId": "C4-MARGINS",
        "index": 711,
        "snippet": "ias—the narrowed margin, sound on paper."
      },
      {
        "clueId": "C8-MAINT",
        "index": 767,
        "snippet": "ressed presence layer, routine on paper."
      },
      {
        "clueId": "C9-MARGINS",
        "index": 815,
        "snippet": "he reframed hazard and the held schedule"
      },
      {
        "clueId": "C12-FOOTNOTES",
        "index": 898,
        "snippet": "led where no one would read it in time.'"
      }
    ]
  },
  "72AG": {
    "slug": "quad-VRPC",
    "markers": [
      {
        "clueId": "C10-SENSITIVE",
        "index": 812,
        "snippet": "ent.\n\n'Elias—you narrowed the threshold."
      },
      {
        "clueId": "C8-CONSOLES",
        "index": 842,
        "snippet": "threshold. Marcus—you overrode the door."
      },
      {
        "clueId": "C11-ALONE",
        "index": 871,
        "snippet": "e the door. Jonah—you skipped the check."
      },
      {
        "clueId": "C12-STANDING",
        "index": 903,
        "snippet": "e check. Renée—you didn't halt in time.'"
      },
      {
        "clueId": "C9-MARK",
        "index": 1091,
        "snippet": "lestone, the deadline that wouldn't bend"
      }
    ]
  },
  "R3X3": {
    "slug": "quad-VSPC",
    "markers": [
      {
        "clueId": "C10-RECAL",
        "index": 678,
        "snippet": "ur were silent.\n\n'Elias—the calibration."
      },
      {
        "clueId": "C9-MARK",
        "index": 698,
        "snippet": "ias—the calibration. Priya—the schedule."
      },
      {
        "clueId": "C11-ALONE",
        "index": 722,
        "snippet": "ya—the schedule. Jonah—the verification."
      },
      {
        "clueId": "C12-SLOW",
        "index": 739,
        "snippet": "Jonah—the verification. Renée—the halt.'"
      },
      {
        "clueId": "C8-DIDNTDENY",
        "index": 1200,
        "snippet": "nswer for it. But a door is just a door."
      }
    ]
  },
  "F7TG": {
    "slug": "quad-RSPC",
    "markers": [
      {
        "clueId": "C10-WARNED",
        "index": 591,
        "snippet": "imeline was irresponsible. He was right."
      },
      {
        "clueId": "C8-MAINT",
        "index": 713,
        "snippet": "\n\n'Marcus—the suppressed presence layer."
      },
      {
        "clueId": "C9-MARK",
        "index": 742,
        "snippet": "ence layer. Priya—the must-run schedule."
      },
      {
        "clueId": "C11-ALONE",
        "index": 767,
        "snippet": "t-run schedule. Jonah—the skipped check."
      },
      {
        "clueId": "C12-SLOW",
        "index": 789,
        "snippet": "the skipped check. Renée—the late halt.'"
      }
    ]
  },
  "Q8YF": {
    "slug": "ellery-herself",
    "markers": [
      {
        "clueId": "C8-BADGE",
        "index": 2299,
        "snippet": "ternoon against a temporary credential.'"
      },
      {
        "clueId": "PRO-AUDITOR",
        "index": 3478,
        "snippet": "unior safety auditor named Mara Ellery.'"
      },
      {
        "clueId": "PRO-ACCEPTABLE",
        "index": 4138,
        "snippet": "r name under the words _acceptable loss_"
      }
    ]
  }
};
