using System.Text.Json;
using AiMysteries.Api.Models;

namespace AiMysteries.Api.Services;

// Reads book content from disk: each immediate subfolder of the given root is a book, named by
// its folder (e.g. "within-tolerance"). This is the dev + authoring source of truth — the
// markdown/JSON files the gen-xrefs pipeline produces. The Tools project reuses it to seed
// Cosmos and to diff against it.
public sealed class FileBookSource : IBookSource
{
    private static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web);

    private readonly string _root;

    // root is the Content directory containing one folder per book.
    public FileBookSource(string root) => _root = root;

    public IEnumerable<RawBook> LoadAll()
    {
        if (!Directory.Exists(_root))
            throw new DirectoryNotFoundException($"Content directory not found: {_root}");

        foreach (var dir in Directory.GetDirectories(_root))
            yield return LoadBook(Path.GetFileName(dir), dir);
    }

    // On-disk content is static for the life of the process (dev restarts to pick up edits), so
    // the version never changes and BookStore never reloads in File mode.
    public string GetVersion() => "file";

    private static RawBook LoadBook(string id, string dir)
    {
        // Book-level metadata (title, marketing copy, cover URL, payoff, share strings) plus the
        // server-only selection rules and the sync-pipeline version/contentHash. Optional: a book
        // with no meta.json falls back to defaults so it still loads.
        var (meta, selection, version, contentHash) = ReadMeta(Path.Combine(dir, "meta.json"), id);

        // Chapters: order from book.json, bodies from book/<slug>.md
        var chapterMetas = ReadJson<List<ChapterMeta>>(Path.Combine(dir, "book.json"));
        var chapters = chapterMetas
            .Select(c => new ChapterDto(c.Slug, c.Title, ReadMd(dir, "book", c.Slug)))
            .ToList();

        // Endings: metadata from endings.json, bodies from endings/<slug>.md
        var endingMetas = ReadJson<List<EndingMeta>>(Path.Combine(dir, "endings.json"));
        var endings = endingMetas
            .Select(e => new Ending(e.Code, e.Culprits, e.Title, e.Special, e.Slug, ReadMd(dir, "endings", e.Slug)))
            .ToList();

        // Cross-references (generated by scripts/gen-xrefs.cjs).
        var clues = ReadJsonOrEmpty<Dictionary<string, ClueDto>>(Path.Combine(dir, "clues.json"));
        var xref = ReadJsonOrEmpty<Dictionary<string, XrefMeta>>(Path.Combine(dir, "xref-markers.json"))
            .ToDictionary(kv => kv.Key, kv => new XrefEntry(kv.Value.Slug, kv.Value.Markers));

        // Unfamiliar-word definitions. Optional; the term falls back to the entry's key so a
        // minimal `{ "bauta": { "definition": "…" } }` entry works.
        var glossary = ReadJsonOrEmpty<Dictionary<string, GlossaryMeta>>(Path.Combine(dir, "glossary.json"))
            .ToDictionary(
                kv => kv.Key,
                kv => new GlossaryEntryDto(
                    kv.Value.Term ?? kv.Key,
                    kv.Value.Definition ?? "",
                    kv.Value.Aliases ?? new List<string>()));

        return new RawBook(id, meta, chapters, endings, clues, xref, glossary, selection, version, contentHash);
    }

    // meta.json → BookMeta + SelectionRules + sync version/contentHash. Absent file or absent
    // fields fall back to defaults (version/contentHash null when never stamped).
    private static (BookMeta, SelectionRules, string?, string?) ReadMeta(string path, string id)
    {
        var d = File.Exists(path)
            ? JsonSerializer.Deserialize<MetaDoc>(File.ReadAllText(path), Json) ?? new MetaDoc()
            : new MetaDoc();
        var selection = d.Selection is { } s
            ? new SelectionRules(
                s.SentinelCulprit,
                s.CategoryWeights ?? new Dictionary<string, int>(),
                s.SpecialEnding ?? 0)
            : SelectionRules.Default;
        var fallback = BookMeta.Default(id);
        return (new BookMeta(
            Title: d.Title ?? fallback.Title,
            Tags: d.Tags ?? fallback.Tags,
            Published: d.Published ?? fallback.Published,
            WordCount: d.WordCount ?? fallback.WordCount,
            Summary: d.Summary ?? fallback.Summary,
            CoverImage: d.CoverImage ?? fallback.CoverImage,
            CoverAlt: d.CoverAlt ?? fallback.CoverAlt,
            SecretBlurb: d.SecretBlurb ?? fallback.SecretBlurb,
            Payoff: d.Payoff ?? fallback.Payoff,
            CodePlaceholder: d.CodePlaceholder ?? fallback.CodePlaceholder,
            ShareTitle: d.ShareTitle ?? d.Title ?? fallback.ShareTitle,
            ShareText: d.ShareText ?? fallback.ShareText,
            SpecialShareText: d.SpecialShareText ?? fallback.SpecialShareText,
            SpecialReveal: d.SpecialReveal is { } sr
                ? new SpecialReveal(sr.Headline ?? "", sr.Sub ?? "")
                : fallback.SpecialReveal,
            NarrationGender: d.NarrationGender ?? fallback.NarrationGender,
            // Key-sorted so File and Cosmos loads serialize identically (no false fingerprint drift).
            Pronunciations: d.Pronunciations is { } prons
                ? prons.OrderBy(kv => kv.Key, StringComparer.Ordinal).ToDictionary(kv => kv.Key, kv => kv.Value)
                : fallback.Pronunciations,
            ShopItems: d.ShopItems is { } items
                ? items.Select(i => new ShopItemDto(i.Label ?? "", i.Note ?? "", i.Search ?? "", i.Asin ?? "")).ToList()
                : fallback.ShopItems), selection, d.Version, d.ContentHash);
    }

    private static string ReadMd(string dir, string sub, string slug)
    {
        var path = Path.Combine(dir, sub, $"{slug}.md");
        if (!File.Exists(path))
            throw new FileNotFoundException($"Missing content file: {path}");
        return File.ReadAllText(path);
    }

    private static T ReadJson<T>(string path)
    {
        if (!File.Exists(path))
            throw new FileNotFoundException($"Missing content file: {path}");
        return JsonSerializer.Deserialize<T>(File.ReadAllText(path), Json)
            ?? throw new InvalidOperationException($"Empty or invalid JSON: {path}");
    }

    private static T ReadJsonOrEmpty<T>(string path) where T : new() =>
        File.Exists(path) ? JsonSerializer.Deserialize<T>(File.ReadAllText(path), Json) ?? new T() : new T();

    private record ChapterMeta(string Slug, string Title);

    private record EndingMeta(string Code, List<string> Culprits, string Title, string Slug, bool Special = false);

    private record XrefMeta(string Slug, List<XrefMarkerDto> Markers);

    // Nullable mirror of one glossary.json entry — term falls back to the entry key.
    private sealed record GlossaryMeta(string? Term = null, string? Definition = null, List<string>? Aliases = null);

    // Nullable mirror of one meta.json shopItems entry.
    private sealed record ShopItemDoc(string? Label = null, string? Note = null, string? Search = null, string? Asin = null);

    // Nullable mirror of meta.json — every field optional so partial/absent files fall back.
    private sealed record MetaDoc(
        string? Title = null,
        List<string>? Tags = null,
        string? Published = null,
        int? WordCount = null,
        List<string>? Summary = null,
        string? CoverImage = null,
        string? CoverAlt = null,
        string? SecretBlurb = null,
        List<string>? Payoff = null,
        string? CodePlaceholder = null,
        string? ShareTitle = null,
        string? ShareText = null,
        string? SpecialShareText = null,
        SpecialRevealDoc? SpecialReveal = null,
        string? NarrationGender = null,
        Dictionary<string, string>? Pronunciations = null,
        List<ShopItemDoc>? ShopItems = null,
        SelectionDoc? Selection = null,
        string? Version = null,
        string? ContentHash = null);

    private sealed record SpecialRevealDoc(string? Headline = null, string? Sub = null);

    private sealed record SelectionDoc(
        string? SentinelCulprit = null,
        Dictionary<string, int>? CategoryWeights = null,
        int? SpecialEnding = null);
}
