using System.Text.Json;
using System.Text.Json.Serialization;
using AiMysteries.Api.Models;
using AiMysteries.Api.Services;

namespace AiMysteries.Tools;

// Writes a RawBook back out to the on-disk file layout (book.json / book/*.md, endings.json /
// endings/*.md, clues.json, xref-markers.json). Used by `pull` to reconstruct local content
// from Cosmos — for recovery or when the DB was edited directly. clues.json / xref-markers.json
// are normally regenerated by scripts/gen-xrefs.cjs, so reformatting them here is fine.
public static class ContentFiles
{
    private static readonly JsonSerializerOptions Json = new(JsonSerializerDefaults.Web)
    {
        WriteIndented = true,
        DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingDefault,
    };

    public static void Write(string contentRoot, RawBook book)
    {
        var dir = Path.Combine(contentRoot, book.Id);
        Directory.CreateDirectory(Path.Combine(dir, "book"));
        Directory.CreateDirectory(Path.Combine(dir, "endings"));

        // meta.json — book-level metadata (title, summary, cover, payoff, share + special-reveal)
        // plus the server-only selection rules. All-default rules are written as no `selection`
        // key at all, so a book authored without one round-trips unchanged.
        var m = book.Meta;
        var r = book.Selection;
        var selection = r.SentinelCulprit is null && r.CategoryWeights.Count == 0 && r.SpecialEnding == 0
            ? null
            : new SelectionDoc(
                r.SentinelCulprit,
                r.CategoryWeights
                    .OrderBy(kv => kv.Key, StringComparer.Ordinal)
                    .ToDictionary(kv => kv.Key, kv => kv.Value),
                r.SpecialEnding);
        WriteJson(Path.Combine(dir, "meta.json"), new MetaDoc(
            m.Title, m.Tags.ToList(), m.Published, m.WordCount, m.Summary.ToList(),
            m.CoverImage, m.CoverAlt, m.SecretBlurb,
            m.Payoff.ToList(), m.CodePlaceholder, m.ShareTitle, m.ShareText, m.SpecialShareText,
            new SpecialRevealDoc(m.SpecialReveal.Headline, m.SpecialReveal.Sub),
            m.NarrationGender,
            m.ShopItems.Count > 0 ? m.ShopItems.ToList() : null,
            selection, book.Version, book.ContentHash));

        // book.json + book/<slug>.md (chapter order preserved from the manifest)
        var chapterMetas = book.Chapters.Select(c => new ChapterMeta(c.Slug, c.Title)).ToList();
        WriteJson(Path.Combine(dir, "book.json"), chapterMetas);
        foreach (var c in book.Chapters)
            File.WriteAllText(Path.Combine(dir, "book", $"{c.Slug}.md"), c.Body);

        // endings.json + endings/<slug>.md
        var endingMetas = book.Endings
            .Select(e => new EndingMeta(e.Code, e.Culprits.ToList(), e.Title, e.Slug, e.Special))
            .ToList();
        WriteJson(Path.Combine(dir, "endings.json"), endingMetas);
        foreach (var e in book.Endings)
            File.WriteAllText(Path.Combine(dir, "endings", $"{e.Slug}.md"), e.Body);

        // clues.json + xref-markers.json (generated artifacts)
        WriteJson(Path.Combine(dir, "clues.json"), book.Clues);
        var xref = book.Xref.ToDictionary(kv => kv.Key, kv => new XrefMeta(kv.Value.Slug, kv.Value.Markers));
        WriteJson(Path.Combine(dir, "xref-markers.json"), xref);

        // glossary.json — only when the book has one, so glossary-less books stay file-free.
        if (book.Glossary.Count > 0)
            WriteJson(Path.Combine(dir, "glossary.json"), book.Glossary);
    }

    private static void WriteJson<T>(string path, T value) =>
        File.WriteAllText(path, JsonSerializer.Serialize(value, Json));

    private record ChapterMeta(string Slug, string Title);

    // `Special` is omitted when false (DefaultIgnoreCondition), matching the authored endings.json.
    private record EndingMeta(string Code, List<string> Culprits, string Title, string Slug, bool Special);

    private record XrefMeta(string Slug, IReadOnlyList<XrefMarkerDto> Markers);

    // Mirrors meta.json (see FileBookSource). Written back on `pull` for a full round-trip.
    private record MetaDoc(
        string Title,
        List<string> Tags,
        string Published,
        int WordCount,
        List<string> Summary,
        string CoverImage,
        string CoverAlt,
        string SecretBlurb,
        List<string> Payoff,
        string CodePlaceholder,
        string ShareTitle,
        string ShareText,
        string SpecialShareText,
        SpecialRevealDoc SpecialReveal,
        string NarrationGender,
        List<ShopItemDto>? ShopItems,
        SelectionDoc? Selection,
        string? Version,
        string? ContentHash);

    private record SpecialRevealDoc(string Headline, string Sub);

    private record SelectionDoc(
        string? SentinelCulprit,
        Dictionary<string, int> CategoryWeights,
        int SpecialEnding);
}
